/**
 * Generated views.
 *
 * A view is a projection of canonical data and never an authority. Each one
 * records the exact canonical files it was built from, with their hashes, so
 * staleness is a question answered at read time — a change to a bound source
 * makes the view stale, unrelated changes elsewhere do not.
 */
import { readDocument, writeDocument } from './frontmatter.mjs';
import { hashText, readUtf8, writeAtomic, now } from './fs-safe.mjs';
import { FARO_VERSION } from './model.mjs';
import { storePath, readCharter, listRequirements, listRoutes, readItem, exists, sectionText } from './store.mjs';
import { routingFreshness } from './routing.mjs';

const GENERATED_NOTICE =
  '<!-- GENERATED BY FARO — DO NOT EDIT. Edit the canonical source and re-run `faro render`. -->';

/** @typedef {{ relative: string, title: string, build: (store: any) => { body: string, bindings: {path:string,hash:string}[] } }} View */

/** @type {Record<string, View>} */
export const VIEWS = {
  compass: {
    relative: 'views/PROJECT_COMPASS.md',
    title: 'Project Compass',
    build: buildCompass,
  },
  requirements: {
    relative: 'views/REQUIREMENTS.md',
    title: 'Requirement Register',
    build: buildRequirements,
  },
  routes: {
    relative: 'views/ROUTES.md',
    title: 'Route Register',
    build: buildRoutes,
  },
};

/**
 * Render one view and write it atomically.
 * @param {import('./store.mjs').Store} store
 * @param {keyof VIEWS} name
 */
export function renderView(store, name) {
  const view = VIEWS[name];
  const { body, bindings } = view.build(store);
  const data = {
    faro_type: 'view',
    generated: true,
    generator: `faro ${FARO_VERSION} (${name})`,
    generated_at: now(),
    source_bindings: bindings,
  };
  const text = writeDocument(data, `${GENERATED_NOTICE}\n\n${body}`);
  writeAtomic(storePath(store, view.relative), text);
  return { relative: view.relative, bindings };
}

/** Render every view. @param {import('./store.mjs').Store} store */
export function renderAllViews(store) {
  return Object.keys(VIEWS).map((name) => renderView(store, name));
}

/**
 * Compare a view against the canonical data it claims to be built from.
 * @param {import('./store.mjs').Store} store
 * @param {keyof VIEWS} name
 * `unverifiable` means the canonical source itself is broken, so the view's
 * freshness cannot be decided. That underlying failure is reported on its own;
 * the view does not report it a second time.
 *
 * @returns {{ name: string, relative: string, state: 'fresh'|'missing'|'stale'|'invalid'|'unverifiable', reason?: string }}
 */
export function viewStatus(store, name) {
  const view = VIEWS[name];
  const result = { name, relative: view.relative };
  let expected;
  try {
    expected = view.build(store).bindings;
  } catch (err) {
    return { ...result, state: 'unverifiable', reason: `cannot rebuild from canonical data — ${err.message}` };
  }
  if (!exists(store, view.relative)) {
    return { ...result, state: 'missing', reason: 'the generated view does not exist' };
  }
  let recorded;
  try {
    const { data } = readDocument(readUtf8(storePath(store, view.relative)), view.relative);
    if (data.faro_type !== 'view' || data.generated !== true || !Array.isArray(data.source_bindings)) {
      return { ...result, state: 'invalid', reason: 'the view is missing its generated-view front matter' };
    }
    recorded = data.source_bindings;
  } catch (err) {
    return { ...result, state: 'invalid', reason: err.message };
  }
  const recordedMap = new Map(recorded.map((entry) => [entry.path, entry.hash]));
  const expectedMap = new Map(expected.map((entry) => [entry.path, entry.hash]));
  for (const [path, hash] of expectedMap) {
    if (!recordedMap.has(path)) {
      return { ...result, state: 'stale', reason: `${path} is not covered by the view` };
    }
    if (recordedMap.get(path) !== hash) {
      return { ...result, state: 'stale', reason: `${path} changed since the view was generated` };
    }
  }
  for (const path of recordedMap.keys()) {
    if (!expectedMap.has(path)) {
      return { ...result, state: 'stale', reason: `${path} no longer exists` };
    }
  }
  return { ...result, state: 'fresh' };
}

/** @param {import('./store.mjs').Store} store */
export function allViewStatuses(store) {
  return Object.keys(VIEWS).map((name) => viewStatus(store, name));
}

/* ---------------------------------------------------------------- builders */

function buildCompass(store) {
  const charter = readCharter(store);
  const c = charter.data;
  const lines = [];
  lines.push('# Project Compass');
  lines.push('');
  lines.push(`Charter version ${c.charter_version} · status \`${c.status}\` · updated ${c.updated_at}`);
  lines.push('');
  lines.push('## Vision');
  lines.push('');
  lines.push(sectionText(charter.body, 'Vision') || '_Not yet stated._');
  lines.push('');
  lines.push('## Problem');
  lines.push('');
  lines.push(sectionText(charter.body, 'Problem') || '_Not yet stated._');
  lines.push('');
  lines.push(renderTable('Objectives', ['ID', 'Objective', 'Statement'], c.objectives, (o) => [o.id, o.title, o.statement]));
  lines.push(renderTable('Deliveries', ['ID', 'Delivery', 'Description'], c.deliveries, (d) => [d.id, d.title, d.description]));
  lines.push(renderTable('Milestones', ['ID', 'Milestone', 'Exit outcome'], c.milestones, (m) => [m.id, m.title, m.outcome]));

  lines.push('## Scope');
  lines.push('');
  lines.push('**In scope**');
  lines.push('');
  lines.push(...bullets(c.scope.included));
  lines.push('');
  lines.push('**Out of scope**');
  lines.push('');
  lines.push(...bullets(c.scope.excluded));
  lines.push('');
  lines.push(renderTable('Principles', ['ID', 'Kind', 'Principle'], c.principles, (p) => [p.id, p.kind, p.statement]));
  lines.push(renderTable('Success measures', ['ID', 'Measure'], c.success_measures, (m) => [m.id, m.statement]));
  lines.push(
    renderTable('Stakeholders and decision authority', ['ID', 'Name', 'Role', 'Decides'], c.stakeholders, (s) => [
      s.id,
      s.name,
      s.role,
      s.decision_authority.join(', ') || '—',
    ]),
  );
  return { body: lines.join('\n').replace(/\n{3,}/g, '\n\n').trim(), bindings: [binding(store, 'charter/charter.md')] };
}

function buildRequirements(store) {
  const charter = readCharter(store);
  const deliveries = new Map(charter.data.deliveries.map((d) => [d.id, d.title]));
  const bindings = [binding(store, 'charter/charter.md')];
  const rows = [];
  for (const entry of listRequirements(store)) {
    if (entry.latest === 0) continue;
    const relative = `requirements/${entry.id}/v${entry.latest}.md`;
    bindings.push(binding(store, relative));
    const item = readItem(store, relative, 'requirement');
    rows.push([
      `${item.data.id}@${item.data.version}`,
      item.data.title,
      `\`${item.data.status}\``,
      (item.data.contributes_to_deliveries ?? []).map((id) => deliveries.get(id) ?? id).join(', ') || '—',
      (item.data.aligns_to_objectives ?? []).join(', ') || '—',
    ]);
  }
  const lines = ['# Requirement Register', ''];
  lines.push('Latest version of every requirement. Historical versions stay on disk and are never rewritten.');
  lines.push('');
  if (rows.length === 0) {
    lines.push('_No requirements have been admitted yet. Capture one with `/faro-intake`._');
  } else {
    lines.push('| Version | Requirement | Status | Deliveries | Objectives |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const row of rows) lines.push(`| ${row.join(' | ')} |`);
  }
  return { body: lines.join('\n'), bindings };
}

/**
 * One route register, not four status views.
 *
 * Stale and review-required routes are *sections* of the register rather than
 * views of their own: a second generated file answering "which routes need
 * attention?" would be a second place to look and a second thing to keep true.
 */
function buildRoutes(store) {
  const bindings = [];
  const rows = [];
  for (const id of listRoutes(store)) {
    const relative = `routes/${id}.md`;
    bindings.push(binding(store, relative));
    const route = readItem(store, relative, 'route');
    const data = route.data;
    const source = readSignatureSource(store, data.signature);
    const freshness = routingFreshness(store, data);
    rows.push({
      id,
      source,
      signature: data.signature,
      status: data.status,
      confidence: data.routing_confidence,
      isolation: data.execution_boundary?.recommended_isolation ?? '—',
      write: (data.scope?.write_scope ?? []).length,
      approval: data.approval?.required === 'human' ? (data.approval.granted ? 'approved' : 'awaiting') : 'auto',
      fresh: freshness.fresh,
      reason: freshness.changed[0] ?? null,
      open: ['draft', 'review_required', 'approved'].includes(data.status),
    });
  }

  const lines = ['# Route Register', ''];
  lines.push('Every route contract, and the exact source each one compiled. A route is usable only');
  lines.push('while its bindings are fresh; staleness is computed here, never stored.');
  lines.push('');
  if (rows.length === 0) {
    lines.push('_No routes yet. Compile one with `/faro-route <REQ-ID@VERSION | OBL-ID>`._');
    return { body: lines.join('\n'), bindings };
  }

  lines.push('| Route | Source | Signature | Status | Confidence | Isolation | Writes | Approval | Bindings |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const row of rows) {
    lines.push(
      `| ${row.id} | ${row.source} | ${row.signature} | \`${row.status}\` | ${row.confidence} | ${row.isolation} | ${row.write} | ${row.approval} | ${row.fresh ? 'fresh' : 'STALE'} |`,
    );
  }

  const stale = rows.filter((row) => row.open && !row.fresh);
  if (stale.length > 0) {
    lines.push('', '## Stale routes', '');
    lines.push('These cannot be used until they are rebased and reconsidered.', '');
    for (const row of stale) lines.push(`- **${row.id}** — ${row.reason}`);
  }

  const review = rows.filter((row) => row.open && row.approval === 'awaiting');
  if (review.length > 0) {
    lines.push('', '## Routes awaiting human approval', '');
    for (const row of review) lines.push(`- **${row.id}** (${row.source}) — ${row.confidence} confidence, ${row.isolation} isolation`);
  }

  return { body: lines.join('\n'), bindings };
}

/** The requirement version or obligation a signature compiled, for display. */
function readSignatureSource(store, signatureId) {
  try {
    const signature = readItem(store, `signatures/${signatureId}.md`, 'signature');
    const source = signature.data.source;
    return source.version ? `${source.id}@${source.version}` : source.id;
  } catch {
    return '(unresolved)';
  }
}

function renderTable(heading, columns, rows, project) {
  const lines = [`## ${heading}`, ''];
  if (!rows || rows.length === 0) {
    lines.push('_None recorded yet._', '');
    return lines.join('\n');
  }
  lines.push(`| ${columns.join(' | ')} |`);
  lines.push(`| ${columns.map(() => '---').join(' | ')} |`);
  for (const row of rows) lines.push(`| ${project(row).join(' | ')} |`);
  lines.push('');
  return lines.join('\n');
}

function bullets(values) {
  if (!values || values.length === 0) return ['_None recorded yet._'];
  return values.map((value) => `- ${value}`);
}

function binding(store, relative) {
  return { path: relative, hash: hashText(readUtf8(storePath(store, relative))) };
}
